<a href="https://colab.research.google.com/github/SebasMore07/Transmisi-n/blob/main/Copia_de_Matrices_transmisi%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matriz inversa

In [ ]:
# Matriz inversa

import numpy as np

# Definir la matriz
matrix = np.array([
    [8.119, 1.819, 0.8243, 0.3291, 0.8655, 0.8243],
    [1.819, 8.099, 1.231, 0.5334, 0.5334, 0.3185],
    [0.8243, 1.231, 8.119, 0.2941, 1.231, 0.3291],
    [0.3291, 0.5334, 0.2941, 8.119, 0.5334, 0.8243],
    [0.8655, 0.5334, 1.231, 0.5334, 8.099, 1.231],
    [0.8243, 0.3185, 0.3291, 0.8243, 1.231, 8.119]
])

# Calcular la inversa
inverse_matrix = np.linalg.inv(matrix)

# Redondear a 4 decimales
rounded_inverse_matrix = np.round(inverse_matrix, 4)

matriz= np.round(rounded_inverse_matrix*(55.55),4)

matriz2 = np.round(rounded_inverse_matrix*(120*np.pi),4)

matriz2 = np.round(matriz*(0.06*2*np.pi),4)

# Mostrar la matriz inversa redondeada
# print(rounded_inverse_matrix)
# print(matriz)
print(matriz2)

[[ 2.7685 -0.5738 -0.1529 -0.0335 -0.1989 -0.2178]
 [-0.5738  2.7811 -0.3497 -0.1424 -0.0565 -0.0126]
 [-0.1529 -0.3497  2.7057 -0.0419 -0.3665 -0.021 ]
 [-0.0335 -0.1424 -0.0419  2.624  -0.1173 -0.2387]
 [-0.1989 -0.0565 -0.3665 -0.1173  2.7287 -0.3644]
 [-0.2178 -0.0126 -0.021  -0.2387 -0.3644  2.6827]]


Reducción de kron

In [ ]:
import numpy as np

def kron_reduction(Z):
    """
    Realiza la reducción de Kron eliminando los conductores de guarda (últimas dos filas y columnas).
    :param Z: Matriz de impedancias original (NxN).
    :return: Matriz reducida sin los conductores de guarda.
    """
    # Índices de los nodos a eliminar (últimos dos en este caso)
    n = Z.shape[0]
    idx_remove = [n-2, n-1]  # Últimos dos índices para las guardas

    # Particionar la matriz en bloques
    Zaa = np.delete(np.delete(Z, idx_remove, axis=0), idx_remove, axis=1)  # Parte que nos interesa
    Zab = np.delete(Z[:, idx_remove], idx_remove, axis=0)  # Interacción entre conductores y guardas
    Zbb = Z[np.ix_(idx_remove, idx_remove)]  # Impedancia de las guardas

    # Invertir Zbb
    Zbb_inv = np.linalg.inv(Zbb)

    # Aplicar reducción de Kron: Z_reducida = Zaa - Zab @ Zbb_inv @ Zab.T
    Z_reducida = Zaa - Zab @ Zbb_inv @ Zab.T

    return Z_reducida

# Definir la matriz de impedancias complejas (8x8) basada en tu tabla
Z = np.array([
    [1.4199 + 1j*890.23,  0.0592 + 1j*400.66,  0.0592 + 1j*348.41,  0.0592 + 1j*309.24,  0.0592 + 1j*331.86,  0.0592 + 1j*336.84,  0.7362 + 1j*0.3554,  0.0592 + 1j*0.3153],
    [0.0592 + 1j*400.66,  1.4199 + 1j*890.23,  0.0592 + 1j*400.66,  0.0592 + 1j*331.86,  0.0592 + 1j*336.84,  0.0592 + 1j*331.86,  0.0592 + 1j*0.32254, 0.0592 + 1j*0.3005],
    [0.0592 + 1j*348.41,  0.0592 + 1j*400.66,  1.4199 + 1j*890.23,  0.0592 + 1j*336.84,  0.0592 + 1j*331.86,  0.0592 + 1j*309.24,  0.0592 + 1j*0.2998,  0.0592 + 1j*0.2844],
    [0.0592 + 1j*309.24,  0.0592 + 1j*331.86,  0.0592 + 1j*336.84,  1.4199 + 1j*890.23,  0.0592 + 1j*400.66,  0.0592 + 1j*348.41,  0.0592 + 1j*0.2844,  0.0592 + 1j*0.2998],
    [0.0592 + 1j*331.86,  0.0592 + 1j*336.84,  0.0592 + 1j*331.86,  0.0592 + 1j*400.66,  1.4199 + 1j*890.23,  0.0592 + 1j*400.66,  0.0592 + 1j*0.3005, 0.0592 + 1j*0.32554],
    [0.0592 + 1j*336.84,  0.0592 + 1j*331.86,  0.0592 + 1j*309.24,  0.0592 + 1j*348.41,  0.0592 + 1j*400.66,  1.4199 + 1j*890.23,  0.0592 + 1j*0.3153,  0.0592 + 1j*0.554],
    [0.7362 + 1j*0.3554,  0.0592 + 1j*0.32254, 0.0592 + 1j*0.2998,  0.0592 + 1j*0.2844,  0.0592 + 1j*0.3005, 0.0592 + 1j*0.3153,  0.7362 + 1j*890.2268,  0.0592 + 1j*0.3306],
    [0.0592 + 1j*0.3153,  0.0592 + 1j*0.3005,  0.0592 + 1j*0.2844,  0.0592 + 1j*0.2998,  0.0592 + 1j*0.32254,  0.0592 + 1j*0.3554,  0.0592 + 1j*0.3306,  0.7362 + 1j*0.2268]
])

# Aplicar reducción de Kron
Z_reducida = kron_reduction(Z)

# Imprimir la nueva matriz reducida
print("Matriz de impedancias reducida:")
print(Z_reducida)


Matriz de impedancias reducida:
[[1.52410322+890.14775481j 0.15818468+400.57998518j
  0.15227178+348.33310771j 0.15796292+309.16013222j
  0.16743548+331.77514621j 0.25163269+336.71093086j]
 [0.15818468+400.57998518j 1.51389151+890.15265445j
  0.14755903+400.58569002j 0.15295345+331.78279643j
  0.16196215+336.75794874j 0.24194405+331.73495668j]
 [0.15227178+348.33310771j 0.14755903+400.58569002j
  1.50294784+890.15862614j 0.14733467+336.76582687j
  0.15582955+331.78113773j 0.23125005+309.11955013j]
 [0.15796292+309.16013222j 0.15295345+331.78279643j
  0.14733467+336.76582687j 1.51341597+890.15293661j
  0.16170275+400.57809627j 0.24149003+348.28516399j]
 [0.16743548+331.77514621j 0.16196215+336.75794874j
  0.15582955+331.78113773j 0.16170275+400.57809627j
  1.53221123+890.14300269j 0.25859311+400.52782431j]
 [0.25163269+336.71093086j 0.24194405+331.73495668j
  0.23125005+309.11955013j 0.24149003+348.28516399j
  0.25859311+400.52782431j 1.77113229+890.03270588j]]


Matriz lambda

In [ ]:
import numpy as np

# Definir la matriz original
lambda_matrix = np.array([
    [8.119, 1.819, 0.8243, 0.3291, 0.8655, 0.8243, 2.8822, 1.0209],
    [1.819, 8.099, 1.231, 0.5334, 0.5334, 0.3185, 9.422, 7.076],
    [0.8243, 1.231, 8.119, 0.2941, 1.231, 0.3291, 4.913, 3.738],
    [0.3291, 0.5334, 0.2941, 8.119, 0.5334, 0.8243, 3.738, 4.913],
    [0.8655, 0.5334, 1.231, 0.5334, 8.099, 1.231, 7.076, 9.422],
    [0.8243, 0.3185, 0.3291, 0.8243, 1.231, 8.119, 1.0209, 2.8822],
    [2.8822, 9.422, 4.913, 3.738, 7.076, 1.0209, 8.119, 8.8002],
    [1.0209, 7.076, 3.738, 4.913, 9.422, 2.8822, 8.8002, 8.119]
])

# Filas y columnas a eliminar (G1 y G2)
rows_to_remove = [6, 7]
cols_to_remove = [6, 7]

# Extraer la submatriz de nodos que quedan (FF)
lambda_FF = np.delete(lambda_matrix, rows_to_remove, axis=0)
lambda_FF = np.delete(lambda_FF, cols_to_remove, axis=1)

# Extraer la submatriz de interacciones (FG)
lambda_FG = lambda_matrix[np.ix_([0, 1, 2, 3, 4, 5], [6, 7])]

# Extraer la submatriz de nodos eliminados (GG)
lambda_GG = lambda_matrix[6:, 6:]

# Calcular la inversa de la matriz GG
lambda_GG_inv = np.linalg.inv(lambda_GG)

# Aplicar la reducción de Kron
lambda_KF = lambda_FF - lambda_FG @ lambda_GG_inv @ lambda_FG.T

# Mostrar resultados
print("Matriz Original:")
print(lambda_matrix)
print("\nMatriz KFF:")
print(lambda_KF)

Matriz Original:
[[8.119  1.819  0.8243 0.3291 0.8655 0.8243 2.8822 1.0209]
 [1.819  8.099  1.231  0.5334 0.5334 0.3185 9.422  7.076 ]
 [0.8243 1.231  8.119  0.2941 1.231  0.3291 4.913  3.738 ]
 [0.3291 0.5334 0.2941 8.119  0.5334 0.8243 3.738  4.913 ]
 [0.8655 0.5334 1.231  0.5334 8.099  1.231  7.076  9.422 ]
 [0.8243 0.3185 0.3291 0.8243 1.231  8.119  1.0209 2.8822]
 [2.8822 9.422  4.913  3.738  7.076  1.0209 8.119  8.8002]
 [1.0209 7.076  3.738  4.913  9.422  2.8822 8.8002 8.119 ]]

Matriz KFF:
[[ 10.211689     3.1211199    1.43172353  -2.2740277   -4.24255303
   -2.16879739]
 [  3.1211199    4.09507824  -0.96351311  -5.70772203 -11.54996392
   -4.78955303]
 [  1.43172353  -0.96351311   6.92069451  -2.93095974  -5.01012203
   -2.2740277 ]
 [ -2.2740277   -5.70772203  -2.93095974   6.92069451  -1.66111311
    1.43172353]
 [ -4.24255303 -11.54996392  -5.01012203  -1.66111311   4.09507824
    2.5331199 ]
 [ -2.16879739  -4.78955303  -2.2740277    1.43172353   2.5331199
   10.211689  ]]

Desbalance matriz de impedancias

In [ ]:
import numpy as np

# Datos de la matriz de impedancias extraídos del taller (sin cables de guarda)
Z_matrix = np.array([
    [1.4199 + 1j*890.23, 0.0592 + 1j*400.66, 0.0592 + 1j*348.41],
    [0.0592 + 1j*400.66, 1.4199 + 1j*890.23, 0.0592 + 1j*331.86],
    [0.0592 + 1j*348.41, 0.0592 + 1j*331.86, 1.4199 + 1j*890.23]
])

# Cálculo del desbalance porcentual
Z_ii = np.diag(Z_matrix)  # Elementos propios (diagonal)
Z_ij = np.triu(Z_matrix, 1)  # Elementos mutuos superiores

# Diferencias relativas con la diagonal
desbalance_percent = np.abs(Z_ij - Z_ij.T) / np.abs(Z_ii) * 100

# Obtener el mayor desbalance
max_desbalance = np.nanmax(desbalance_percent)  # nanmax ignora los valores NaN

max_desbalance


45.006289918573614

Desbalance matriz admitancias

In [ ]:
# Datos de la matriz de admitancias extraídos del taller (sin cables de guarda)
Y_matrix = np.array([
    [8.119, 1.819, 0.8243],
    [1.819, 8.099, 1.231],
    [0.8243, 1.231, 8.119]
])

# Cálculo del desbalance porcentual en la matriz de admitancias
Y_ii = np.diag(Y_matrix)  # Elementos propios (diagonal)
Y_ij = np.triu(Y_matrix, 1)  # Elementos mutuos superiores

# Diferencias relativas con la diagonal
desbalance_percent_Y = np.abs(Y_ij - Y_ij.T) / np.abs(Y_ii) * 100

# Obtener el mayor desbalance en admitancias
max_desbalance_Y = np.nanmax(desbalance_percent_Y)  # nanmax ignora los valores NaN

max_desbalance_Y


22.45956290900111